# Generated by Django 4.2.6 on 2023-10-14 15:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Todoapp', '0004_rename_name_tsk_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsk',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
